### ISSUE TITLE
[BUG]  /avatar 命令顯示錯誤

### ISSUE THREAD

**Issue by Youzi9601** [friedshrimptaiwan/FSBOT#1]
**詳細說明錯誤(BUG)**
> 預設玩家頭像無法正常顯示，只能顯示非預設頭像者的頭像

**備註**
你改了/userinfo 卻忘記改這東西 owo|||

**照片**
![image](https://user-images.githubusercontent.com/93034834/169251015-dfe8eee7-7fe4-4a37-aa9f-45ff770bfad6.png)

**Comment by Youzi9601** [comment]
我猜我講之前userinfo的問題之後你沒想到這命力吧(我倒是有想了一下，不對，這也不是相同問題嗎www)

**Comment by VincentX0905** [comment]
已修復!
fixed!
