### ISSUE TITLE
[BUG] 自訂的表情符號顯示錯誤

### ISSUE THREAD

**Issue by Youzi9601** [friedshrimptaiwan/FSBOT#2]
**詳細說明錯誤(BUG)**
> 自訂之表情符號顯示為文字

**如何重現這個錯誤(BUG)**
詳細說明如何重現這個錯誤(BUG)
> 1. 輸入任何會需要"讀取中..."的命令
> 2. 出現了！

**截圖**
> ![image](https://user-images.githubusercontent.com/93034834/169299485-ca60fda1-4086-4841-b91f-7e20ea9c0414.png)

**備註**
建議： 如果表情符號名稱為 "Discovery", 請在機器人訊息處的 :Discovery: 改成 <:Discovery:894962564415492216>
這樣才能在其他伺服器中做使用！

**Comment by VincentX0905** [comment]
> 待確認是否為discord bug
已經嘗試過部分群組可以部分群組無法

**Comment by Youzi9601** [comment]
Discord 本身的Bug，懸案做結

**Comment by VincentX0905** [comment]
經過調查發現
如果您關閉了機器人 `使用外部表情符號` 權限
或是關閉頻道 `使用外部表情符號` 權限
或是關閉everyone身分組 `使用外部表情符號` 權限
將會出現此問題，此為Discord Bug，故無法修復!
