### ISSUE TITLE
[BUG] 有關所有嵌入訊息都會因為字數限制而無法發送

### ISSUE THREAD

**Issue by Youzi9601** [friedshrimptaiwan/FSBOT#5]
`直接於>後方輸入即可`

**詳細說明錯誤(BUG)**
> 沒有防範字數限制

**如何重現這個錯誤(BUG)**
詳細說明如何重現這個錯誤(BUG)
> 1. aaaa到底

**截圖**
請使用 `Google Drive(記得開分享)` 或是 `Discord` 連結
非以上兩者之連結皆不會點開查看!
> ![image](https://user-images.githubusercontent.com/93034834/170045154-33daeee7-fafc-4902-a7c8-9227a848ee25.png)

~~(喔乾...我的YZB好像也有這問題 :rofl:~~

**Comment by Youzi9601** [comment]
(不要問我最後一個後面為啥放這個(`print(quit())`)

**Comment by VincentX0905** [comment]
全數已修復
感謝回報!
