### ISSUE TITLE
[BUG] 日誌輸出 - 編輯訊息

### ISSUE THREAD

**Issue by Youzi9601** [friedshrimptaiwan/FSBOT#6]
**詳細說明錯誤(BUG)**
> 只要訊息涉及 .gif 或是 圖片連結的，Discord會直接顯示該檔案... 但是...不應該送出 訊息編輯 ... 
![image](https://user-images.githubusercontent.com/93034834/172135475-c83dd17f-26b0-442f-b2e9-3906b50c5fd1.png)
https://discord.com/channels/937628164862136362/980623548731256833/983299383019839538

**如何重現這個錯誤(BUG)**
詳細說明如何重現這個錯誤(BUG)
> 1. 炸蝦 傳送一個Gif連結
> 2. Gif被Discord直接顯示
> 3. 機器人偵測到了"訊息編輯"
> 4. 柚子看了紀錄....編輯前與編輯後84一樣的ㄇ?

**備註**
其他的像是客戶端....並無此問題。

**Comment by VincentX0905** [comment]
目前應該是已經全數修復了，正在觀察是否有例外
